"""
Synthetic Spiral Film Roll Dataset Generator
=============================================
Creates synthetic CT-like cross-sections of wound film rolls by rolling
a 2D strip image into an Archimedean spiral.  Produces HDF5 files compatible
with the existing unwrapping pipeline, plus ground truth for evaluation.

The spiral is modelled as concentric ring-like windings (matching real CT
cross-sections).  Each winding carries a thin emulsion layer whose intensity
comes from the source strip, and a uniform film-base layer.

Usage:
    python -m unwrapping.synthetic.generate --preset quick_test
    python -m unwrapping.synthetic.generate --preset clean_4k --output-dir results/synthetic
"""

import argparse
import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional, Tuple

import h5py
import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ═══════════════════════════════════════════════════════════════════════════
# Parameters
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class SpiralParams:
    """Parameters defining the spiral geometry and rendering."""

    image_size: int = 512           # output image H=W (square)
    n_windings: int = 15            # number of spiral windings
    film_thickness: float = 12.0    # total radial thickness of film (px)
    emulsion_fraction: float = 0.18 # fraction of film that is emulsion
    air_gap: float = 4.0            # radial air gap between windings (px)
    n_z_slices: int = 5             # depth slices in the volume
    pattern: str = "frames"         # strip pattern type

    # video source (only used when pattern="video")
    video_path: Optional[str] = None

    # emulsion placement
    emulsion_side: str = "inner"    # "inner" or "outer" radial edge

    # imperfection controls
    noise_std: float = 0.0          # additive Gaussian noise sigma
    eccentricity: float = 0.0       # spiral center offset (px)
    radial_jitter: float = 0.0      # per-winding radial perturbation (px)
    # Path 3: jitter spectrum. "sinusoidal" (default) = 3-component sin sum,
    # original behavior. "1f" = 1/f-spectrum spatial noise generated by
    # taking iFFT of a random spectrum scaled by 1/sqrt(freq), better
    # mimicking real film tension noise (broadband, more low-frequency).
    jitter_spectrum: str = "sinusoidal"
    # Path 3: per-slice segmentation imperfections that mimic real nnU-Net
    # residual error.
    #   seg_pinch_points: number of random 1-2px radial bridges injected
    #     between consecutive windings PER Z-SLICE (different per z).
    #   seg_mislabel_rate: fraction of (film_base, emulsion) pixels flipped
    #     between each other per-slice (independent per z), in addition to
    #     the additive noise_std on intensity.
    seg_pinch_points: int = 0
    seg_mislabel_rate: float = 0.0

    # ── realistic (spatially-coherent) segmentation error ────────────────
    # Real nnU-Net error is NOT salt-and-pepper (that's what seg_mislabel_rate
    # gives); it is spatially coherent at class boundaries, concentrated at
    # the film-base↔emulsion interface, with air almost always correct. These
    # three knobs model that. All default 0 (legacy: no effect).
    #   seg_boundary_wobble: the base↔emulsion boundary shifts by up to this
    #     many px in coherent angular runs (driven by smooth low-freq noise),
    #     emulsion locally grows or retreats. Mimics edge uncertainty.
    #   seg_content_thicken: where emulsion CONTENT is bright (high silver /
    #     exposure), the predicted emulsion band thickens by up to this many
    #     px, growing isotropically but capped to the film mask (cannot cross
    #     the air gap into the next winding). Mimics the real model's tendency
    #     to over-segment emulsion under bright content.
    #   seg_content_thicken_thresh: strip-content fraction [0,1] above which
    #     thickening engages (brightness gate).
    #   seg_air_clip_rate: fraction of the film/air boundary that gets
    #     coherently clipped to air (a small 1-2px bite in connected runs).
    #     Mimics the model occasionally clipping the film edge against air.
    seg_boundary_wobble: float = 0.0
    seg_content_thicken: float = 0.0
    seg_content_thicken_thresh: float = 0.5
    seg_air_clip_rate: float = 0.0

    # rendering intensities  (model real CT absorption)
    #   air         ~ 0.02  (very low absorption)
    #   film base   ~ 0.12  (dark plastic / cellulose)
    #   emulsion @0 ~ 0.12  (unexposed = same as base, no silver)
    #   emulsion @1 ~ 0.85  (fully exposed = dense silver grains, bright in CT)
    background_intensity: float = 0.02
    film_base_intensity: float = 0.12
    emulsion_max_intensity: float = 0.85

    center: Optional[Tuple[float, float]] = None  # (cy, cx); None = image center

    # Track 5: optional override for innermost-winding centerline radius.
    # Default behavior (None) keeps the historical `layer_spacing * 3`. Set
    # this to match a real volume's r_inner exactly so the synthetic→real
    # transfer of the INR residual is in matching pixel-scale.
    r_inner_override: Optional[float] = None

    # ── derived ──────────────────────────────────────────────────────────
    @property
    def layer_spacing(self) -> float:
        return self.film_thickness + self.air_gap

    @property
    def emulsion_thickness(self) -> float:
        return self.film_thickness * self.emulsion_fraction

    @property
    def r_inner(self) -> float:
        """Innermost winding centerline radius (leaves room for spool core)."""
        if self.r_inner_override is not None:
            return float(self.r_inner_override)
        return self.layer_spacing * 3

    @property
    def r_outer(self) -> float:
        return self.r_inner + self.layer_spacing * (self.n_windings - 1)

    @property
    def spiral_advance(self) -> float:
        """Radial advance per radian: a in  r = r0 + a*theta."""
        return self.layer_spacing / (2 * np.pi)

    def get_center(self) -> Tuple[float, float]:
        if self.center is None:
            c = self.image_size / 2.0
            return (c, c)
        return self.center

    def compute_strip_length(self) -> int:
        """Approximate total spiral arc-length in pixels."""
        a = self.spiral_advance
        theta_max = 2 * np.pi * self.n_windings
        return int(self.r_inner * theta_max + 0.5 * a * theta_max ** 2)

    def to_dict(self) -> dict:
        d = {k: getattr(self, k) for k in [
            "image_size", "n_windings", "film_thickness", "emulsion_fraction",
            "air_gap", "n_z_slices", "pattern", "emulsion_side",
            "noise_std", "eccentricity", "radial_jitter",
            "jitter_spectrum", "seg_pinch_points", "seg_mislabel_rate",
            "seg_boundary_wobble", "seg_content_thicken",
            "seg_content_thicken_thresh", "seg_air_clip_rate",
            "background_intensity", "film_base_intensity",
            "emulsion_max_intensity",
        ]}
        if self.r_inner_override is not None:
            d["r_inner_override"] = self.r_inner_override
        if self.video_path is not None:
            d["video_path"] = self.video_path
        return d


# ═══════════════════════════════════════════════════════════════════════════
# Presets
# ═══════════════════════════════════════════════════════════════════════════

PRESETS: Dict[str, SpiralParams] = {
    # Phase 1 — quick verification (small, clean)
    "quick_test": SpiralParams(
        image_size=512, n_windings=15, film_thickness=12, air_gap=4,
        n_z_slices=5, pattern="frames",
    ),
    # Phase 2 — 4K variants
    "clean_4k": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, pattern="frames",
    ),
    "noisy_4k": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, noise_std=0.05, pattern="frames",
    ),
    "tight_4k": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=3,
        n_z_slices=20, pattern="frames",
    ),
    "imperfect_4k": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, noise_std=0.03, eccentricity=10.0, radial_jitter=5.0,
        pattern="frames",
    ),
    # Phase 2 — outer-edge emulsion variants
    "clean_4k_outer": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, pattern="frames", emulsion_side="outer",
    ),
    "imperfect_4k_outer": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, noise_std=0.03, eccentricity=10.0, radial_jitter=5.0,
        pattern="frames", emulsion_side="outer",
    ),
    # Phase 2 — real video variants (require --video <path>)
    "video_4k": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, pattern="video",
    ),
    "video_4k_imperfect": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, noise_std=0.03, eccentricity=10.0, radial_jitter=5.0,
        pattern="video",
    ),
    "video_4k_outer": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, pattern="video", emulsion_side="outer",
    ),
    "video_4k_outer_harsh": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=20, noise_std=0.08, eccentricity=30.0, radial_jitter=12.0,
        pattern="video", emulsion_side="outer",
    ),
    # Track 5 — synthetic preset matched to real Mickey geometry, used for
    # supervised pretraining before SS fine-tuning on real Mickey.
    # Real Mickey (raycast-detected on volume_0836-0855):
    #   34 windings, ~17px film_thickness, ~5px air_gap (≈22px spacing),
    #   r ∈ [617, 1347] in a 3063×3062 image.
    # Image size 3063 to match real exactly so the INR's residual is in
    # consistent pixel-to-normalized scale. Mild ecc/jitter to encode the
    # organic variability we expect in real (small relative to imperfect_4k's
    # 10/5).
    "mickey_geometry": SpiralParams(
        image_size=3063, n_windings=34, film_thickness=17, air_gap=5,
        n_z_slices=20, pattern="video",
        eccentricity=8.0, radial_jitter=4.0, noise_std=0.02,
        r_inner_override=617.0, emulsion_side="inner",    ),
    # Track 5 / Path 3 — strengthened mickey-matched preset with realistic
    # imperfections. Same geometry as `mickey_geometry`, plus:
    #   - 1/f-spectrum radial jitter (broadband film tension noise instead of
    #     3-component sinusoidal — matches real spectrum).
    #   - seg_mislabel_rate=0.03 ≈ our nnU-Net 3D 0.97 Dice residual error.
    #   - seg_pinch_points=8: random radial bridges between adjacent windings,
    #     varying per-slice. Mimics real CT segmentation pinch artifacts.
    # Used to train R1S supervised → fine-tune on real Mickey via R1T5 path.
    "mickey_geometry_v2": SpiralParams(
        image_size=3063, n_windings=34, film_thickness=17, air_gap=5,
        n_z_slices=20, pattern="video",
        eccentricity=8.0, radial_jitter=4.0, noise_std=0.02,
        r_inner_override=617.0, emulsion_side="inner",
        jitter_spectrum="1f",
        seg_pinch_points=8,
        seg_mislabel_rate=0.03,    ),
    # High-resolution preset for visualizing reconstruction detail. Designed
    # for the presentation: feed in a high-quality video (e.g. Big Buck
    # Bunny 1080p), use many z-slices so the unrolled strip is hundreds of
    # pixels tall and fine content detail is visible. Geometry is similar
    # to clean_4k for fast convergence; the point is content fidelity, not
    # geometric stress-testing.
    "hq_video_4k": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=256, pattern="video",    ),
    # Outer-emulsion variants of hq_video_4k. The thesis pipeline supports
    # both inner- and outer-emulsion film stocks; outer is closer to many
    # real archival reels. Same n_z=256 for fine detail.
    "hq_video_4k_outer": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=256, pattern="video", emulsion_side="outer",    ),
    "hq_video_4k_outer_imperfect": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=256, pattern="video", emulsion_side="outer",
        noise_std=0.03, eccentricity=10.0, radial_jitter=5.0,    ),
    # Realistic imperfect: 1/f (broadband) radial jitter matching real film
    # tension noise, plus segmentation imperfections (pinch points +
    # mislabelling) that mimic nnU-Net residual error. Mild ecc/jitter. This
    # is the closest HQ-outer analogue of real Mickey short of matching its
    # exact winding count. Continuous-jitter pipeline (no seam cut).
    "hq_video_4k_outer_realistic": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=256, pattern="video", emulsion_side="outer",
        noise_std=0.02, eccentricity=8.0, radial_jitter=4.0,
        jitter_spectrum="1f", seg_pinch_points=8,
        # Spatially-coherent, real-nnU-Net-like segmentation error (replaces
        # the old salt-and-pepper seg_mislabel_rate=0.03 which looked jagged):
        #   - air almost perfect, only a small coherent film/air edge clip
        #   - dominant error is the base↔emulsion boundary wobble
        #   - emulsion over-segmented (thicker) under bright content
        seg_mislabel_rate=0.0,
        seg_boundary_wobble=1.5,
        seg_content_thicken=2.0,
        seg_content_thicken_thresh=0.5,
        seg_air_clip_rate=0.03,    ),
    # Harsh stress preset: strong eccentricity + large jitter + heavy noise.
    # Upper bound on geometric difficulty; for robustness stress-testing.
    "hq_video_4k_outer_harsh": SpiralParams(
        image_size=4096, n_windings=28, film_thickness=36, air_gap=12,
        n_z_slices=256, pattern="video", emulsion_side="outer",
        noise_std=0.08, eccentricity=30.0, radial_jitter=12.0,    ),
}


# ═══════════════════════════════════════════════════════════════════════════
# Strip Pattern Generators
# ═══════════════════════════════════════════════════════════════════════════

def generate_strip(
    width: int, height: int, pattern: str = "frames",
    video_path: str = None,
) -> np.ndarray:
    """Generate a 2D test-pattern strip  (height, width)  in [0, 1]."""
    if pattern == "video":
        return _video_strip(width, height, video_path)
    fn = {
        "gradient": _gradient_strip,
        "bars": _bars_strip,
        "frames": _frames_strip,
        "composite": _composite_strip,
    }
    if pattern not in fn:
        raise ValueError(f"Unknown pattern '{pattern}'. Choose from {list(fn)}")
    return fn[pattern](width, height)


def _gradient_strip(w: int, h: int) -> np.ndarray:
    """Smooth horizontal gradient — value == normalised position."""
    return np.tile(
        np.linspace(0.1, 0.9, w, dtype=np.float32)[np.newaxis, :], (h, 1)
    )


def _bars_strip(w: int, h: int) -> np.ndarray:
    """Alternating vertical bars."""
    bar_w = max(w // 40, 10)
    x = np.arange(w)
    row = ((x // bar_w) % 2).astype(np.float32) * 0.6 + 0.2
    return np.tile(row[np.newaxis, :], (h, 1))


def _frames_strip(w: int, h: int) -> np.ndarray:
    """Simulated movie frames with per-frame unique patterns."""
    strip = np.full((h, w), 0.15, dtype=np.float32)
    frame_w = max(200, h * 4 // 3)  # wide enough to be recognisable
    n_frames = w // frame_w + 1

    yy_full, xx_full = np.mgrid[0:h, 0:w]

    for i in range(n_frames):
        x0 = i * frame_w
        x1 = min(x0 + frame_w, w)
        if x0 >= w:
            break
        lx = xx_full[:, x0:x1] - x0
        ly = yy_full[:, x0:x1]
        fw = x1 - x0

        # unique diagonal stripes
        angle = i * 0.4 + 0.2
        period = max(h // 3, 8)
        wave = np.sin(
            2 * np.pi * (lx * np.cos(angle) + ly * np.sin(angle)) / period
        )
        base = 0.3 + 0.4 * ((i * 7) % 11) / 10.0
        content = base + 0.15 * wave

        # circle in each frame (simulates a character / object)
        cx_f, cy_f = fw // 2, h // 2
        r_circle = min(fw, h) * 0.22
        dist = np.sqrt((lx - cx_f) ** 2 + (ly - cy_f) ** 2)
        content = np.where(dist < r_circle, content + 0.15, content)

        # thin frame border
        bw = max(1, h // 20)
        content[:bw, :] = 0.10
        content[-bw:, :] = 0.10
        content[:, :min(bw, fw)] = 0.10

        strip[:, x0:x1] = np.clip(content, 0.05, 0.95)

    # perforation holes along top / bottom
    perf_sp = frame_w // 2
    perf_sz = max(h // 8, 2)
    for px in range(perf_sz, w, perf_sp):
        p0 = max(px - perf_sz // 2, 0)
        p1 = min(px + perf_sz // 2, w)
        strip[:perf_sz, p0:p1] = 0.05
        strip[-perf_sz:, p0:p1] = 0.05

    return strip


def _composite_strip(w: int, h: int) -> np.ndarray:
    """Frames blended with a positional gradient."""
    return np.clip(
        0.7 * _frames_strip(w, h) + 0.3 * _gradient_strip(w, h), 0, 1
    )


def _video_strip(w: int, h: int, video_path: str = None) -> np.ndarray:
    """Build a strip from real video frames.

    Extracts frames from a video file, converts to grayscale, resizes each
    frame to (h, frame_w) and tiles them horizontally to fill the strip.
    Values are normalised to [0, 1].
    """
    if video_path is None:
        raise ValueError("video_path is required for pattern='video'")

    import imageio.v3 as iio
    from PIL import Image

    video_path = str(video_path)
    frame_w = max(200, h * 4 // 3)
    n_frames_needed = (w + frame_w - 1) // frame_w

    # Read all frames (lazy generator) and collect what we need
    frames = []
    for frame_rgb in iio.imiter(video_path):
        # Convert to grayscale: standard luminance weights
        if frame_rgb.ndim == 3 and frame_rgb.shape[2] >= 3:
            gray = (
                0.2989 * frame_rgb[:, :, 0].astype(np.float32)
                + 0.5870 * frame_rgb[:, :, 1].astype(np.float32)
                + 0.1140 * frame_rgb[:, :, 2].astype(np.float32)
            )
        elif frame_rgb.ndim == 2:
            gray = frame_rgb.astype(np.float32)
        else:
            gray = frame_rgb[:, :, 0].astype(np.float32)

        # Normalise to [0, 1]
        gray = gray / 255.0

        # Resize to (h, frame_w) using Pillow
        pil = Image.fromarray((gray * 255).astype(np.uint8), mode="L")
        pil = pil.resize((frame_w, h), Image.LANCZOS)
        frames.append(np.asarray(pil).astype(np.float32) / 255.0)

        if len(frames) >= n_frames_needed:
            break

    if len(frames) == 0:
        raise ValueError(f"Could not read any frames from {video_path}")

    # If video is too short, loop frames
    while len(frames) < n_frames_needed:
        frames.extend(frames[: n_frames_needed - len(frames)])

    # Tile horizontally and trim to exact width
    strip = np.concatenate(frames, axis=1)[:, :w]

    # Clip to valid range
    strip = np.clip(strip, 0.0, 1.0)

    n_used = min(n_frames_needed, len(frames))
    print(f"    video: {n_used} frames extracted, resized to {h}x{frame_w} each")
    return strip


# ═══════════════════════════════════════════════════════════════════════════
# Spiral Geometry  (computed once, reused for every z-slice)
# ═══════════════════════════════════════════════════════════════════════════

def compute_spiral_geometry(params: SpiralParams, strip_width: int) -> dict:
    """Pre-compute all geometry arrays shared across z-slices.

    Returns a dict with boolean masks, segmentation template, u-map template,
    and interpolation indices/weights into the source strip.
    """
    H = W = params.image_size
    cy, cx = params.get_center()
    a = params.spiral_advance

    # coordinate grids (float32 to save memory at 4K)
    yy, xx = np.mgrid[0:H, 0:W]
    yy = yy.astype(np.float32)
    xx = xx.astype(np.float32)

    r = np.sqrt((yy - cy) ** 2 + (xx - cx) ** 2)
    theta = np.arctan2(yy - cy, xx - cx) % (2 * np.pi)

    # ── eccentricity: shift effective radius (≈ off-centre spool) ─────
    if params.eccentricity > 0:
        r = r + params.eccentricity * np.cos(theta - np.pi / 4)

    # ── winding assignment ────────────────────────────────────────────
    k_cont = (r - params.r_inner - a * theta) / params.layer_spacing
    k = np.rint(k_cont).astype(np.int32)

    # Continuous strip angle: θ wraps 2π→0 at the +x seam ray while k jumps
    # k→k+1 there, so θ_total = θ + 2πk is *continuous* across the seam. All
    # geometry that must be seam-continuous (centerline, jitter, arc length)
    # is expressed in θ_total — never in (θ, k) separately. Doing the latter
    # for the jitter is exactly what produced the visible radial "cut" along
    # the +x ray in the imperfect presets (the jitter stepped by up to
    # radial_jitter px when k jumped at the seam). Real film is one
    # continuous strip, so its tension perturbation is continuous here too.
    theta_total = theta + 2 * np.pi * k.astype(np.float32)

    # centerline radius for nearest winding (continuous across seam)
    r_center = params.r_inner + a * theta_total

    # ── per-winding radial jitter (continuous in θ_total) ─────────────
    if params.radial_jitter > 0:
        if params.jitter_spectrum == "1f":
            # 1/f spatial noise as ONE continuous sequence over the full
            # strip coordinate θ_total ∈ [0, 2π·n_windings]. Generating it as
            # a single sequence (rather than a per-winding table indexed by
            # (k, θ)) guarantees continuity across the seam: adjacent windings
            # share the boundary sample. Generate complex Fourier coefficients
            # with magnitude ∝ 1/sqrt(freq) and random phase; iFFT gives
            # broadband real-valued noise.
            rng = np.random.default_rng(seed=12345)  # deterministic per preset
            n_per_wind = 1024
            N = params.n_windings * n_per_wind
            freqs = np.fft.rfftfreq(N, d=1.0)
            freqs[0] = 1.0  # avoid div-by-zero (DC handled separately)
            scale = 1.0 / np.sqrt(freqs)
            scale[0] = 0.0  # zero-mean (no DC bias)
            spec = (rng.standard_normal(len(freqs))
                    + 1j * rng.standard_normal(len(freqs))) * scale
            seq = np.fft.irfft(spec, n=N).astype(np.float32)
            # Normalize to PEAK=radial_jitter. Peak-normalization is critical
            # because the synthetic u_map computes winding index via
            # `k = rint(k_cont)` using ideal pixel-radius — when jitter peaks
            # exceed half the layer_spacing, pixels near peaks get assigned to
            # the wrong winding and the GT u_map is corrupted.
            seq = seq / (np.abs(seq).max() + 1e-9) * params.radial_jitter
            # Continuously index the sequence by θ_total (linear interp).
            theta_max = 2 * np.pi * params.n_windings
            pos = np.clip(theta_total / theta_max, 0.0, 1.0) * (N - 1)
            i0 = np.floor(pos).astype(np.int64)
            i1 = np.minimum(i0 + 1, N - 1)
            fr = (pos - i0).astype(np.float32)
            jitter = seq[i0] * (1.0 - fr) + seq[i1] * fr
            del pos, i0, i1, fr
        else:  # "sinusoidal" (default)
            # Multi-scale sinusoids in θ_total. The low-frequency component
            # (≈1 cycle per 3 windings) supplies the slow winding-to-winding
            # variation that the legacy `+ k*phase` term provided, but
            # continuously — no seam step.
            jitter = params.radial_jitter * (
                0.5 * np.sin(theta_total * 2.0 + 0.7)
                + 0.3 * np.sin(theta_total * 5.0 + 1.3)
                + 0.2 * np.sin(theta_total * 0.31 + 2.1)
            )
        r_center = r_center + jitter

    # signed radial distance from winding centerline
    dr = r - r_center
    half_t = params.film_thickness / 2.0

    # masks
    on_film = (np.abs(dr) <= half_t) & (k >= 0) & (k < params.n_windings)
    emul_t = params.emulsion_thickness
    if params.emulsion_side == "outer":
        # emulsion on the outer radial edge (larger r)
        on_emulsion = on_film & (dr <= half_t) & (dr > half_t - emul_t)
    else:
        # emulsion on the inner radial edge (smaller r)
        on_emulsion = on_film & (dr >= -half_t) & (dr < -half_t + emul_t)
    on_base = on_film & ~on_emulsion

    # segmentation template (same for every z)
    seg = np.zeros((H, W), dtype=np.uint8)
    seg[on_base] = 1
    seg[on_emulsion] = 2

    # ── arc-length → strip u-coordinate ───────────────────────────────
    arc = params.r_inner * theta_total + 0.5 * a * theta_total ** 2
    theta_max = 2 * np.pi * params.n_windings
    total_arc = params.r_inner * theta_max + 0.5 * a * theta_max ** 2
    u_norm = np.clip(arc / total_arc, 0, 1)  # normalised [0,1]

    u_map = np.full((H, W), np.nan, dtype=np.float32)
    u_map[on_film] = u_norm[on_film]

    # interpolation indices into strip
    u_pixel = u_norm * (strip_width - 1)
    u_pixel = np.clip(u_pixel, 0, strip_width - 1)
    u_floor = np.floor(u_pixel).astype(np.int32)
    u_ceil = np.minimum(u_floor + 1, strip_width - 1)
    u_frac = (u_pixel - u_floor).astype(np.float32)

    # free large intermediates
    del yy, xx, r, theta, k_cont, k, r_center, dr, theta_total, arc, u_norm, u_pixel

    return dict(
        seg=seg, u_map=u_map,
        on_film=on_film, on_base=on_base, on_emulsion=on_emulsion,
        u_floor=u_floor, u_ceil=u_ceil, u_frac=u_frac,
    )


# ═══════════════════════════════════════════════════════════════════════════
# Slice Rendering
# ═══════════════════════════════════════════════════════════════════════════

def render_slice(
    strip_row: np.ndarray,
    geo: dict,
    params: SpiralParams,
) -> np.ndarray:
    """Render one z-slice from a single strip row + pre-computed geometry.

    Returns (H, W) float32 image in [0, 1].
    """
    H = W = params.image_size
    base = params.film_base_intensity
    image = np.full((H, W), params.background_intensity, dtype=np.float32)
    image[geo["on_base"]] = base

    # bilinear interpolation of strip content [0,1]
    strip_val = (
        strip_row[geo["u_floor"]] * (1.0 - geo["u_frac"])
        + strip_row[geo["u_ceil"]] * geo["u_frac"]
    )
    # map strip content to CT absorption:
    #   strip=0 (black/unexposed) -> same as film base (dark, no silver)
    #   strip=1 (white/exposed)   -> emulsion_max (bright, dense silver)
    silver = strip_val * (params.emulsion_max_intensity - base)
    emul_intensity = base + silver
    image[geo["on_emulsion"]] = emul_intensity[geo["on_emulsion"]]

    if params.noise_std > 0:
        noise = np.random.normal(0, params.noise_std, (H, W)).astype(np.float32)
        image = np.clip(image + noise, 0, 1)

    return image


# ═══════════════════════════════════════════════════════════════════════════
# Save helpers
# ═══════════════════════════════════════════════════════════════════════════

def _dilate(mask: np.ndarray, r: int) -> np.ndarray:
    """4-neighbour binary dilation by `r` px (numpy-only, no scipy)."""
    m = mask
    for _ in range(int(r)):
        out = m.copy()
        out[1:, :] |= m[:-1, :]
        out[:-1, :] |= m[1:, :]
        out[:, 1:] |= m[:, :-1]
        out[:, :-1] |= m[:, 1:]
        m = out
    return m


def _erode(mask: np.ndarray, r: int) -> np.ndarray:
    return ~_dilate(~mask, r)


def _coarse_noise(
    H: int, W: int, cell: int, rng: np.random.Generator
) -> np.ndarray:
    """Smooth low-frequency noise field ~N(0,1), coherent at scale ~`cell` px.

    Random values on a coarse grid, bilinearly upsampled. Used to drive
    spatially-coherent (not salt-and-pepper) segmentation perturbations.
    """
    gh, gw = H // cell + 2, W // cell + 2
    g = rng.standard_normal((gh, gw)).astype(np.float32)
    ys = np.linspace(0, gh - 1, H).astype(np.float32)
    xs = np.linspace(0, gw - 1, W).astype(np.float32)
    y0 = np.floor(ys).astype(np.int32)
    x0 = np.floor(xs).astype(np.int32)
    y1 = np.minimum(y0 + 1, gh - 1)
    x1 = np.minimum(x0 + 1, gw - 1)
    fy = (ys - y0)[:, None]
    fx = (xs - x0)[None, :]
    top = g[y0][:, x0] * (1 - fx) + g[y0][:, x1] * fx
    bot = g[y1][:, x0] * (1 - fx) + g[y1][:, x1] * fx
    return top * (1 - fy) + bot * fy


def _perturb_seg(
    seg: np.ndarray,
    params: SpiralParams,
    geo: dict,
    image: np.ndarray,
    rng: np.random.Generator,
) -> np.ndarray:
    """Apply per-slice segmentation perturbations.

    Realistic (spatially-coherent) effects, in order:
      1. Air-edge clip — small coherent 1-2px bites of the film/air boundary
         relabelled to air (`seg_air_clip_rate`).
      2. Content thickening — emulsion band grows isotropically (≤
         `seg_content_thicken` px, capped to the film mask) where the rendered
         emulsion content is bright (gate `seg_content_thicken_thresh`).
      3. Boundary wobble — base↔emulsion interface shifts ±`seg_boundary_wobble`
         px in coherent angular runs (smooth-noise driven).
    Legacy effects retained (default off): per-pixel `seg_mislabel_rate`
    salt-and-pepper, and `seg_pinch_points` radial bridges.
    """
    out = seg.copy()
    H, W = out.shape

    # ── 1. Coherent air ↔ film-base edge clip ─────────────────────────
    if params.seg_air_clip_rate > 0:
        rate = float(params.seg_air_clip_rate)
        on_film = (out == 1) | (out == 2)
        # 1px film rim adjacent to air.
        film_edge = on_film & ~_erode(on_film, 1)
        n = _coarse_noise(H, W, cell=40, rng=rng)
        ne = n[film_edge]
        if ne.size > 0:
            thr = np.quantile(ne, 1.0 - rate)
            clip = film_edge & (n > thr)
            # Grow the bite 1px so it's a coherent 1-2px nibble, keep on film.
            clip = _dilate(clip, 1) & on_film
            out[clip] = 0

    # ── 2. Content-dependent emulsion thickening (both sides, → base) ──
    if params.seg_content_thicken > 0:
        base_i = params.film_base_intensity
        span = params.emulsion_max_intensity - base_i
        thr_b = base_i + float(params.seg_content_thicken_thresh) * span
        emul = out == 2
        base_m = out == 1
        bright = emul & (image > thr_b)
        grow = _dilate(bright, int(np.ceil(params.seg_content_thicken))) & base_m
        out[grow] = 2

    # ── 3. Coherent base ↔ emulsion boundary wobble ───────────────────
    if params.seg_boundary_wobble > 0:
        w = int(np.ceil(params.seg_boundary_wobble))
        emul = out == 2
        base_m = out == 1
        n = _coarse_noise(H, W, cell=35, rng=rng)
        near_emul = base_m & _dilate(emul, w)   # base within w px of emulsion
        near_base = emul & _dilate(base_m, w)   # emulsion within w px of base
        # ~upper/lower ~27% tails flip → mild, coherent ±~1-2px wobble.
        out[near_emul & (n > 0.6)] = 2          # emulsion locally grows
        out[near_base & (n < -0.6)] = 1         # emulsion locally retreats

    # ── Legacy: per-pixel mislabel speckle (default off) ──────────────
    if params.seg_mislabel_rate > 0:
        rate = float(params.seg_mislabel_rate)
        on_film = (out == 1) | (out == 2)
        flip = (rng.random(out.shape) < rate) & on_film
        rand_label = rng.integers(1, 3, size=out.shape, dtype=np.uint8)
        out[flip] = rand_label[flip]

    # ── Pinch points: radial 1-2px bridges between adjacent windings ───
    n_pp = int(params.seg_pinch_points)
    if n_pp > 0 and params.n_windings >= 2:
        cy, cx = params.get_center()
        a = params.spiral_advance
        for _ in range(n_pp):
            # Pick a random adjacent-winding pair k → k+1.
            k = int(rng.integers(0, params.n_windings - 1))
            # Pick a random angle θ uniformly in [0, 2π).
            theta = float(rng.uniform(0, 2 * np.pi))
            # Centerline radii at this θ for windings k and k+1.
            r_k = params.r_inner + a * (theta + 2 * np.pi * k)
            r_kp1 = params.r_inner + a * (theta + 2 * np.pi * (k + 1))
            # Bridge spans from inner edge of k's emulsion to outer edge of
            # k+1's emulsion (≈ across the air gap).
            r_lo = r_k + 0.5 * params.film_thickness
            r_hi = r_kp1 - 0.5 * params.film_thickness
            if r_lo >= r_hi:
                continue  # touching windings (no air gap)
            n_steps = int(max(2, np.ceil(r_hi - r_lo))) * 3
            rs = np.linspace(r_lo, r_hi, n_steps)
            # Bridge thickness 1-2 px tangentially (perpendicular to radial).
            bridge_w = float(rng.uniform(1.0, 2.0))
            # Sample tangential offsets in [-bridge_w/2, bridge_w/2].
            n_tan = max(2, int(np.ceil(bridge_w)) * 2)
            tans = np.linspace(-bridge_w / 2, bridge_w / 2, n_tan)
            cos_t, sin_t = np.cos(theta), np.sin(theta)
            # Tangent direction perp to radial.
            tx, ty = -sin_t, cos_t
            for r_v in rs:
                xs = (cx + r_v * cos_t + tans * tx).astype(np.int32)
                ys = (cy + r_v * sin_t + tans * ty).astype(np.int32)
                valid = (xs >= 0) & (xs < W) & (ys >= 0) & (ys < H)
                out[ys[valid], xs[valid]] = 1
    return out


def _seg_to_onehot(seg: np.ndarray, n_classes: int = 3) -> np.ndarray:
    """Convert integer seg-map to one-hot (…, n_classes) float32."""
    oh = np.zeros((*seg.shape, n_classes), dtype=np.float32)
    for c in range(n_classes):
        oh[..., c] = (seg == c).astype(np.float32)
    return oh


def save_dataset(
    strip: np.ndarray,
    geo: dict,
    params: SpiralParams,
    output_dir: Path,
):
    """Render every z-slice and write HDF5 files + ground truth."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    n_z = params.n_z_slices
    H = W = params.image_size
    seg = geo["seg"]
    # Path 3: per-slice segmentation noise (mislabels + pinch points). When
    # enabled, each z gets its own corrupted seg → forces the model to be
    # robust to nnU-Net-style residual error during synthetic training.
    use_seg_noise = (
        params.seg_mislabel_rate > 0 or params.seg_pinch_points > 0
        or params.seg_boundary_wobble > 0 or params.seg_content_thicken > 0
        or params.seg_air_clip_rate > 0
    )
    seg_oh_2d = _seg_to_onehot(seg)  # used when seg noise is disabled
    rng_seg = np.random.default_rng(seed=20260506)

    # ── 3D volume files (written slice-by-slice to save memory) ───────
    vol_path = output_dir / f"volume_0000-{n_z - 1:04d}.h5"
    vol_prob_path = output_dir / f"volume_0000-{n_z - 1:04d}_Probabilities.h5"

    f_vol = h5py.File(vol_path, "w")
    f_prob = h5py.File(vol_prob_path, "w")
    dset_vol = f_vol.create_dataset("volume", shape=(n_z, H, W), dtype=np.uint16)
    dset_prob = f_prob.create_dataset(
        "exported_data", shape=(n_z, H, W, 3), dtype=np.float32,
        compression="gzip", compression_opts=1,
    )

    first_image = None

    for z in range(n_z):
        image = render_slice(strip[z], geo, params)
        img_u16 = (np.clip(image, 0, 1) * 65535).astype(np.uint16)

        # Per-slice noisy seg (path 3) or shared clean seg (default).
        if use_seg_noise:
            seg_z = _perturb_seg(seg, params, geo, image, rng_seg)
            seg_oh_z = _seg_to_onehot(seg_z)
        else:
            seg_oh_z = seg_oh_2d

        # 2D slice files
        with h5py.File(output_dir / f"slice_{z:04d}.h5", "w") as f:
            f.create_dataset("image", data=img_u16)
        with h5py.File(output_dir / f"slice_{z:04d}_Probabilities.h5", "w") as f:
            f.create_dataset("exported_data", data=seg_oh_z)

        # 3D volume
        dset_vol[z] = img_u16
        dset_prob[z] = seg_oh_z

        if z == 0:
            first_image = image.copy()
        if (z + 1) % 5 == 0 or z == n_z - 1:
            print(f"    rendered slice {z + 1}/{n_z}")

    f_vol.close()
    f_prob.close()

    # ── ground truth ──────────────────────────────────────────────────
    gt_path = output_dir / "ground_truth.npz"
    np.savez_compressed(
        gt_path,
        strip=strip,
        u_map=geo["u_map"],
        seg=seg,
        **params.to_dict(),
    )

    # ── params JSON (human-readable) ─────────────────────────────────
    with open(output_dir / "params.json", "w") as f:
        json.dump(params.to_dict(), f, indent=2)

    print(f"  Saved {n_z} 2D slices  +  1 3D volume  ->  {output_dir}")
    return first_image


# ═══════════════════════════════════════════════════════════════════════════
# Verification
# ═══════════════════════════════════════════════════════════════════════════

def verify_roundtrip(
    image: np.ndarray,
    seg: np.ndarray,
    u_map: np.ndarray,
    strip_row: np.ndarray,
    params: SpiralParams,
    output_dir: Path,
):
    """Unroll using ground-truth u-map, compare to original strip row.

    Only uses emulsion pixels (they carry the varying film content).
    Inverts the CT intensity model (base + content*(max-base)) to recover
    the original strip content before comparison.
    Returns RMSE of the recovered strip vs original.
    """
    output_dir = Path(output_dir)
    emul_mask = seg == 2
    u_vals = u_map[emul_mask]
    raw_intensities = image[emul_mask]

    # invert CT intensity model: content = (intensity - base) / (max - base)
    base = params.film_base_intensity
    span = params.emulsion_max_intensity - base
    content = (raw_intensities.astype(np.float64) - base) / span

    n_bins = len(strip_row)
    recovered = np.zeros(n_bins, dtype=np.float64)
    counts = np.zeros(n_bins, dtype=np.int64)

    u_bins = np.clip((u_vals * (n_bins - 1)).astype(np.int64), 0, n_bins - 1)
    np.add.at(recovered, u_bins, content)
    np.add.at(counts, u_bins, 1)

    valid = counts > 0
    recovered[valid] /= counts[valid]

    # metrics (compare recovered content to original strip content)
    both = valid & (strip_row > 0)
    if both.sum() == 0:
        print("  roundtrip: no overlapping pixels!")
        return np.inf

    diff = recovered[both] - strip_row[both].astype(np.float64)
    rmse = float(np.sqrt(np.mean(diff ** 2)))
    max_err = float(np.max(np.abs(diff)))
    coverage = valid.sum() / n_bins
    psnr_db = float(20.0 * np.log10(1.0 / rmse)) if rmse > 0 else float("inf")

    print(f"  roundtrip  RMSE={rmse:.5f}  PSNR={psnr_db:.2f} dB  "
          f"max_err={max_err:.5f}  coverage={coverage:.1%}  "
          f"({valid.sum()}/{n_bins} bins)")

    # ── plot ──────────────────────────────────────────────────────────
    fig, axes = plt.subplots(3, 1, figsize=(14, 6), sharex=True)

    # show a small window for visibility
    show_n = min(2000, n_bins)
    xs = np.arange(show_n)
    axes[0].plot(xs, strip_row[:show_n], "k-", lw=0.5, label="original")
    axes[0].set_ylabel("content")
    axes[0].set_title("Original strip content (first 2000 px)")
    axes[0].legend(fontsize=8)

    axes[1].plot(xs, recovered[:show_n], "b-", lw=0.5, label="recovered")
    axes[1].set_ylabel("content")
    axes[1].set_title(f"Recovered strip content (RMSE={rmse:.5f})")
    axes[1].legend(fontsize=8)

    err_plot = recovered[:show_n] - strip_row[:show_n].astype(np.float64)
    axes[2].plot(xs, err_plot, "r-", lw=0.5)
    axes[2].set_ylabel("error")
    axes[2].set_xlabel("strip position (px)")
    axes[2].set_title("Difference")

    plt.tight_layout()
    plt.savefig(output_dir / "roundtrip_verify.png", dpi=120, bbox_inches="tight")
    plt.close()
    return rmse


# ═══════════════════════════════════════════════════════════════════════════
# Diagnostic Plots
# ═══════════════════════════════════════════════════════════════════════════

def plot_diagnostics(
    image: np.ndarray,
    seg: np.ndarray,
    u_map: np.ndarray,
    strip: np.ndarray,
    params: SpiralParams,
    output_dir: Path,
):
    """Save overview and zoomed diagnostic figures."""
    output_dir = Path(output_dir)

    # ── overview ──────────────────────────────────────────────────────
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))

    axes[0, 0].imshow(strip, cmap="gray", aspect="auto", vmin=0, vmax=1)
    axes[0, 0].set_title(f"Strip  {strip.shape[0]}x{strip.shape[1]}")
    axes[0, 0].set_xlabel("arc-length (px)")
    axes[0, 0].set_ylabel("z-slice")

    axes[0, 1].imshow(image, cmap="gray", vmin=0, vmax=1)
    axes[0, 1].set_title("Rolled image (slice 0)")

    seg_rgb = np.zeros((*seg.shape, 3), dtype=np.float32)
    seg_rgb[seg == 0] = [0.10, 0.10, 0.20]
    seg_rgb[seg == 1] = [0.20, 0.70, 0.20]
    seg_rgb[seg == 2] = [0.90, 0.30, 0.10]
    axes[0, 2].imshow(seg_rgb)
    axes[0, 2].set_title("Segmentation  (air / base / emulsion)")

    im = axes[1, 0].imshow(u_map, cmap="turbo", vmin=0, vmax=1)
    axes[1, 0].set_title("Ground-truth u-map")
    plt.colorbar(im, ax=axes[1, 0], fraction=0.046)

    cy = int(params.get_center()[0])
    axes[1, 1].plot(image[cy, :], "k-", lw=0.4)
    axes[1, 1].set_title(f"Radial profile  (y={cy})")
    axes[1, 1].set_xlabel("x (px)")
    axes[1, 1].set_ylabel("intensity")

    u_valid = u_map[~np.isnan(u_map)]
    axes[1, 2].hist(u_valid, bins=100, color="steelblue", edgecolor="none")
    axes[1, 2].set_title("u-map histogram")
    axes[1, 2].set_xlabel("u")

    plt.suptitle(
        f"Synthetic -- {params.pattern}  |  {params.n_windings} windings  |  "
        f"{params.image_size}x{params.image_size}  |  emulsion={params.emulsion_side}  |  "
        f"noise={params.noise_std}  ecc={params.eccentricity}  jit={params.radial_jitter}",
        fontsize=13,
    )
    plt.tight_layout()
    plt.savefig(output_dir / "diagnostics.png", dpi=150, bbox_inches="tight")
    plt.close()

    # ── zoomed view (3-4 windings) ────────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    zoom_r = int(params.layer_spacing * 4)
    y0 = max(cy - zoom_r, 0)
    y1 = min(cy + zoom_r, params.image_size)
    x0 = cy  # start from centre going right
    x1 = min(cy + zoom_r * 2, params.image_size)

    axes[0].imshow(image[y0:y1, x0:x1], cmap="gray", vmin=0, vmax=1)
    axes[0].set_title("Zoomed: intensity")
    axes[1].imshow(seg_rgb[y0:y1, x0:x1])
    axes[1].set_title("Zoomed: segmentation")
    im = axes[2].imshow(u_map[y0:y1, x0:x1], cmap="turbo")
    axes[2].set_title("Zoomed: u-map")
    plt.colorbar(im, ax=axes[2], fraction=0.046)

    plt.suptitle("Zoomed view  (3-4 windings)", fontsize=13)
    plt.tight_layout()
    plt.savefig(output_dir / "diagnostics_zoom.png", dpi=150, bbox_inches="tight")
    plt.close()

    # ── segmentation class counts ─────────────────────────────────────
    n_total = params.image_size ** 2
    n_air = int((seg == 0).sum())
    n_base = int((seg == 1).sum())
    n_emul = int((seg == 2).sum())
    print(f"  seg classes -- air: {n_air/n_total:.1%}  "
          f"base: {n_base/n_total:.1%}  emulsion: {n_emul/n_total:.1%}")


def plot_strip(strip: np.ndarray, params: SpiralParams, output_dir: Path):
    """Save the original unrolled strip with zoomed crops."""
    output_dir = Path(output_dir)
    h, w = strip.shape
    n_crops = 4
    crop_w = min(800, w // 4)

    fig_h = max(3, 1.5 * (1 + n_crops))
    fig, axes = plt.subplots(1 + n_crops, 1, figsize=(16, fig_h))

    # full strip (compressed)
    axes[0].imshow(strip, cmap="gray", aspect="auto", vmin=0, vmax=1)
    axes[0].set_title(f"Full strip  ({h} x {w} px)")
    axes[0].set_xlabel("arc-length (px)")
    axes[0].set_ylabel("z")

    # zoomed crops at evenly spaced positions
    rng = np.random.RandomState(42)
    positions = np.linspace(0, w - crop_w, n_crops + 2)[1:-1].astype(int)
    # add some randomness
    jitter = rng.randint(-crop_w // 4, crop_w // 4, size=n_crops)
    positions = np.clip(positions + jitter, 0, w - crop_w)

    for i, x0 in enumerate(positions):
        axes[i + 1].imshow(
            strip[:, x0 : x0 + crop_w], cmap="gray", aspect="auto", vmin=0, vmax=1
        )
        pct = x0 / w * 100
        axes[i + 1].set_title(f"Crop @ x={x0}  ({pct:.0f}% along strip)")
        axes[i + 1].set_ylabel("z")

    plt.suptitle(
        f"Original film strip  --  {params.pattern} pattern", fontsize=13
    )
    plt.tight_layout()
    plt.savefig(output_dir / "strip.png", dpi=150, bbox_inches="tight")
    plt.close()


# ═══════════════════════════════════════════════════════════════════════════
# Main Orchestrator
# ═══════════════════════════════════════════════════════════════════════════

def generate_dataset(params: SpiralParams, output_dir: str) -> dict:
    """End-to-end: generate strip, compute geometry, render, save, verify."""
    output_dir = Path(output_dir)
    strip_w = params.compute_strip_length()

    print(f"\n{'=' * 60}")
    print(f"Generating synthetic dataset")
    print(f"  preset params : {params.to_dict()}")
    print(f"  strip size    : {params.n_z_slices} x {strip_w}")
    print(f"  output        : {output_dir}")
    print(f"{'=' * 60}")

    t0 = time.time()
    strip = generate_strip(
        strip_w, params.n_z_slices, params.pattern,
        video_path=params.video_path,
    )
    print(f"  strip generated     {time.time() - t0:.1f}s")

    t1 = time.time()
    geo = compute_spiral_geometry(params, strip_w)
    print(f"  geometry computed   {time.time() - t1:.1f}s")

    t2 = time.time()
    first_image = save_dataset(strip, geo, params, output_dir)
    print(f"  rendering + save   {time.time() - t2:.1f}s")

    plot_diagnostics(first_image, geo["seg"], geo["u_map"], strip, params, output_dir)
    plot_strip(strip, params, output_dir)
    rmse = verify_roundtrip(
        first_image, geo["seg"], geo["u_map"], strip[0], params, output_dir
    )

    total = time.time() - t0
    print(f"  total time         {total:.1f}s")
    print(f"{'=' * 60}\n")

    return {"rmse": rmse, "output_dir": str(output_dir), "strip_shape": strip.shape}


# ═══════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Generate synthetic spiral film-roll datasets"
    )
    parser.add_argument(
        "--preset", default="quick_test", choices=list(PRESETS),
        help="Parameter preset (default: quick_test)",
    )
    parser.add_argument("--output-dir", default=None)
    parser.add_argument(
        "--pattern", default=None,
        choices=["gradient", "bars", "frames", "composite", "video"],
        help="Override strip pattern",
    )
    parser.add_argument(
        "--video", default=None, metavar="PATH",
        help="Path to video file (sets pattern=video automatically)",
    )
    parser.add_argument(
        "--all-phase2", action="store_true",
        help="Generate all Phase 2 (4K) presets",
    )
    args = parser.parse_args()

    if args.all_phase2:
        for name, preset in PRESETS.items():
            if "4k" not in name:
                continue
            # Skip video presets unless --video is provided
            if preset.pattern == "video" and not args.video:
                print(f"  Skipping {name} (needs --video <path>)")
                continue
            if args.video:
                preset.video_path = args.video
            out = args.output_dir or "unwrapping/synthetic/results"
            generate_dataset(preset, f"{out}/{name}")
    else:
        params = PRESETS[args.preset]
        if args.video:
            params.video_path = args.video
            if params.pattern != "video":
                params.pattern = "video"
        elif args.pattern:
            params.pattern = args.pattern
        if params.pattern == "video" and not params.video_path:
            parser.error("--video <path> is required for video presets")
        out = args.output_dir or f"unwrapping/synthetic/results/{args.preset}"
        generate_dataset(params, out)


if __name__ == "__main__":
    main()
